[workspace]
members = [
    ".",
    "xim-gen",
    "xim-parser",
]

[package]
name = "xim"
version = "0.1.0"
authors = ["Riey <creeper844@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
xim-parser = { path = "./xim-parser" }
thiserror = "1.0.22"
x11rb = { version = "0.7.0", features = ["allow-unsafe-code"] }
log = "0.4.11"

[dev-dependencies]
criterion = "0.3.3"
simplelog = "0.8.0"

[[bench]]
name = "rw"
harness = false
