[workspace]
members = [
    ".",
    "xim-gen",
]

[package]
name = "xim"
version = "0.1.0"
authors = ["Riey <creeper844@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
thiserror = "1.0.22"
num-traits = "0.2.14"

[build-dependencies]
xim-gen = { path = "./xim-gen" }

[dev-dependencies]
criterion = "0.3.3"
pretty_assertions = "0.6.1"

[[bench]]
name = "rw"
harness = false
