[workspace]
members = [
    ".",
    "xim-gen",
    "xim-parser",
]

[package]
name = "xim"
version = "0.1.0"
authors = ["Riey <creeper844@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
xim-parser = { path = "./xim-parser" }
xcb = { version = "0.9.0", optional = true }

[dev-dependencies]
criterion = "0.3.3"

[[bench]]
name = "rw"
harness = false
