[package]
name = "xim-parser"
version = "0.1.0"
authors = ["Riey <creeper844@gmail.com>"]
edition = "2018"
license = "MIT"

[dependencies]
thiserror = "1.0.22"
bitflags = "1.2.1"
bstr = "0.2.14"

[dev-dependencies]
pretty_assertions = "0.6.1"

[build-dependencies]
xim-gen = { path = "../xim-gen" }
