[package]
name = "xim-ctext"
description = "compound text en/decoder"
version = "0.2.0"
authors = ["Riey <creeper844@gmail.com>"]
repository = "https://github.com/Riey/xim-rs"
edition = "2018"
license = "MIT"

[dependencies]
encoding_rs = "0.8.28"
thiserror = "1.0.28"
