// DO NOT TOUCH YOURSELF
// This source is auto generated by xim-gen

#![allow(unused)]

use std::convert::TryInto;
use std::fmt;

pub fn read(b: &[u8]) -> Result<Request, ReadError> {
    Request::read(&mut Reader::new(b))
}

pub fn write(req: &Request, out: &mut Vec<u8>) {
    req.write(&mut Writer::new(out));
}

#[derive(Copy, Clone, Debug, Eq, PartialEq)]
#[repr(u8)]
pub enum Endian {
    Big = 0x42,
    Little = 0x6c,
}

#[derive(Debug, thiserror::Error)]
pub enum ReadError {
    #[error("End of Stream")]
    EndOfStream,
    #[error("Invalid Data {0}: {1}")]
    InvalidData(&'static str, String),
    #[error("Not a native endian")]
    NotNativeEndian,
}

fn pad4(len: usize) -> usize {
    (4 - (len % 4)) % 4
}

fn with_pad4(len: usize) -> usize {
    len + pad4(len)
}

pub struct Reader<'b> {
    bytes: &'b [u8],
    start: usize,
}

impl<'b> Reader<'b> {
    pub fn new(bytes: &'b [u8]) -> Self {
        Self {
            bytes,
            start: bytes.as_ptr() as usize,
        }
    }

    fn ptr_offset(&self) -> usize {
        self.bytes.as_ptr() as usize - self.start
    }

    pub fn cursor(&self) -> usize {
        self.bytes.len()
    }

    pub fn pad4(&mut self) -> Result<(), ReadError> {
        self.consume(pad4(self.ptr_offset()))?;
        Ok(())
    }

    pub fn eos(&self) -> ReadError {
        ReadError::EndOfStream
    }

    pub fn invalid_data(&self, ty: &'static str, item: impl ToString) -> ReadError {
        ReadError::InvalidData(ty, item.to_string())
    }

    pub fn u8(&mut self) -> Result<u8, ReadError> {
        let (b, new) = self.bytes.split_first().ok_or(self.eos())?;
        self.bytes = new;
        Ok(*b)
    }

    pub fn u16(&mut self) -> Result<u16, ReadError> {
        let bytes = self.consume(2)?.try_into().unwrap();
        Ok(u16::from_ne_bytes(bytes))
    }

    pub fn u32(&mut self) -> Result<u32, ReadError> {
        let bytes = self.consume(4)?.try_into().unwrap();
        Ok(u32::from_ne_bytes(bytes))
    }

    pub fn i32(&mut self) -> Result<i32, ReadError> {
        let bytes = self.consume(4)?.try_into().unwrap();
        Ok(i32::from_ne_bytes(bytes))
    }

    pub fn consume(&mut self, len: usize) -> Result<&'b [u8], ReadError> {
        if self.bytes.len() >= len {
            let (out, new) = self.bytes.split_at(len);
            self.bytes = new;
            Ok(out)
        } else {
            Err(self.eos())
        }
    }
}

pub struct Writer<'b> {
    out: &'b mut Vec<u8>,
}

impl<'b> Writer<'b> {
    pub fn new(out: &'b mut Vec<u8>) -> Self {
        Self { out }
    }

    pub fn write_u8(&mut self, b: u8) {
        self.out.push(b);
    }

    pub fn write(&mut self, bytes: &[u8]) {
        self.out.extend_from_slice(bytes);
    }

    pub fn write_pad4(&mut self) {
        let pad = pad4(self.out.len());
        self.out.extend(std::iter::repeat(0).take(pad));
    }
}

pub trait XimFormat<'b>: Sized {
    fn read(reader: &mut Reader<'b>) -> Result<Self, ReadError>;
    fn write(&self, writer: &mut Writer);
    /// byte size of format
    fn size(&self) -> usize;
}

#[derive(Copy, Clone, Eq, PartialEq)]
pub struct XimString<'b>(pub &'b [u8]);

impl<'a> fmt::Display for XimString<'a> {
    fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {
        f.write_str(std::str::from_utf8(self.0).unwrap_or("NOT_UTF8"))
    }
}

impl<'a> fmt::Debug for XimString<'a> {
    fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {
        f.write_str(std::str::from_utf8(self.0).unwrap_or("NOT_UTF8"))
    }
}

impl<'b> XimFormat<'b> for Endian {
    fn read(reader: &mut Reader<'b>) -> Result<Self, ReadError> {
        let n = u8::read(reader)?;

        if n == Endian::Little as u8 && cfg!(target_endian = "little") {
            Ok(Self::Little)
        } else if n == Endian::Big as u8 && cfg!(target_endian = "big") {
            Ok(Self::Big)
        } else {
            Err(ReadError::NotNativeEndian)
        }
    }

    fn write(&self, writer: &mut Writer) {
        (*self as u8).write(writer);
    }

    fn size(&self) -> usize {
        1
    }
}

impl<'b> XimFormat<'b> for u8 {
    fn read(reader: &mut Reader<'b>) -> Result<Self, ReadError> {
        reader.u8()
    }

    fn write(&self, writer: &mut Writer) {
        writer.write_u8(*self)
    }

    fn size(&self) -> usize {
        1
    }
}

impl<'b> XimFormat<'b> for u16 {
    fn read(reader: &mut Reader<'b>) -> Result<Self, ReadError> {
        reader.u16()
    }

    fn write(&self, writer: &mut Writer) {
        writer.write(&self.to_ne_bytes())
    }

    fn size(&self) -> usize {
        2
    }
}

impl<'b> XimFormat<'b> for u32 {
    fn read(reader: &mut Reader<'b>) -> Result<Self, ReadError> {
        reader.u32()
    }

    fn write(&self, writer: &mut Writer) {
        writer.write(&self.to_ne_bytes())
    }

    fn size(&self) -> usize {
        4
    }
}
impl<'b> XimFormat<'b> for i32 {
    fn read(reader: &mut Reader<'b>) -> Result<Self, ReadError> {
        reader.i32()
    }

    fn write(&self, writer: &mut Writer) {
        writer.write(&self.to_ne_bytes())
    }

    fn size(&self) -> usize {
        4
    }
}
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
#[repr(u16)]
pub enum AttrType {
    Separator = 0,
    Byte = 1,
    Word = 2,
    Long = 3,
    Char = 4,
    Window = 5,
    Style = 10,
    XRectangle = 11,
    XPoint = 12,
    XFontSet = 13,
    HotkeyTriggers = 15,
    StringConversion = 17,
    PreeditState = 18,
    ResetState = 19,
    NestedList = 32767,
}
impl<'b> XimFormat<'b> for AttrType {
    fn read(reader: &mut Reader<'b>) -> Result<Self, ReadError> {
        let repr = u16::read(reader)?;
        match repr {
            0 => Ok(Self::Separator),
            1 => Ok(Self::Byte),
            2 => Ok(Self::Word),
            3 => Ok(Self::Long),
            4 => Ok(Self::Char),
            5 => Ok(Self::Window),
            10 => Ok(Self::Style),
            11 => Ok(Self::XRectangle),
            12 => Ok(Self::XPoint),
            13 => Ok(Self::XFontSet),
            15 => Ok(Self::HotkeyTriggers),
            17 => Ok(Self::StringConversion),
            18 => Ok(Self::PreeditState),
            19 => Ok(Self::ResetState),
            32767 => Ok(Self::NestedList),
            _ => Err(reader.invalid_data("AttrType", repr)),
        }
    }
    fn write(&self, writer: &mut Writer) {
        (*self as u16).write(writer);
    }
    fn size(&self) -> usize {
        std::mem::size_of::<u16>()
    }
}
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
#[repr(u32)]
pub enum CaretStyle {
    Invisible = 0,
    Primary = 1,
    Secondary = 2,
}
impl<'b> XimFormat<'b> for CaretStyle {
    fn read(reader: &mut Reader<'b>) -> Result<Self, ReadError> {
        let repr = u32::read(reader)?;
        match repr {
            0 => Ok(Self::Invisible),
            1 => Ok(Self::Primary),
            2 => Ok(Self::Secondary),
            _ => Err(reader.invalid_data("CaretStyle", repr)),
        }
    }
    fn write(&self, writer: &mut Writer) {
        (*self as u32).write(writer);
    }
    fn size(&self) -> usize {
        std::mem::size_of::<u32>()
    }
}
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct Attr<'b> {
    pub id: u16,
    pub ty: AttrType,
    pub name: XimString<'b>,
}
impl<'b> XimFormat<'b> for Attr<'b> {
    fn read(reader: &mut Reader<'b>) -> Result<Self, ReadError> {
        Ok(Self {
            id: <u16 as XimFormat<'b>>::read(reader)?,
            ty: <AttrType as XimFormat<'b>>::read(reader)?,
            name: {
                let inner = {
                    let len = u16::read(reader)?;
                    let bytes = reader.consume(len as usize)?;
                    XimString(bytes)
                };
                reader.pad4()?;
                inner
            },
        })
    }
    fn write(&self, writer: &mut Writer) {
        self.id.write(writer);
        self.ty.write(writer);
        (self.name.0.len() as u16).write(writer);
        writer.write(self.name.0);
        writer.write_pad4();
    }
    fn size(&self) -> usize {
        let mut content_size = 0;
        content_size += self.id.size();
        content_size += self.ty.size();
        content_size += with_pad4(self.name.0.len() + 2);
        content_size
    }
}
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct Extension<'b> {
    pub major_opcode: u8,
    pub minor_opcode: u8,
    pub name: XimString<'b>,
}
impl<'b> XimFormat<'b> for Extension<'b> {
    fn read(reader: &mut Reader<'b>) -> Result<Self, ReadError> {
        Ok(Self {
            major_opcode: <u8 as XimFormat<'b>>::read(reader)?,
            minor_opcode: <u8 as XimFormat<'b>>::read(reader)?,
            name: {
                let inner = {
                    let len = u16::read(reader)?;
                    let bytes = reader.consume(len as usize)?;
                    XimString(bytes)
                };
                reader.pad4()?;
                inner
            },
        })
    }
    fn write(&self, writer: &mut Writer) {
        self.major_opcode.write(writer);
        self.minor_opcode.write(writer);
        (self.name.0.len() as u16).write(writer);
        writer.write(self.name.0);
        writer.write_pad4();
    }
    fn size(&self) -> usize {
        let mut content_size = 0;
        content_size += self.major_opcode.size();
        content_size += self.minor_opcode.size();
        content_size += with_pad4(self.name.0.len() + 2);
        content_size
    }
}
#[derive(Debug, Clone, Eq, PartialEq)]
pub enum Request<'b> {
    AuthNext {},
    AuthNg {},
    AuthReply {},
    AuthRequired {},
    AuthSetup {},
    Close {
        input_method_id: u16,
    },
    CloseReply {
        input_method_id: u16,
    },
    Commit {},
    Connect {
        endian: Endian,
        client_major_protocol_version: u16,
        client_minor_protocol_version: u16,
        client_auth_protocol_names: Vec<XimString<'b>>,
    },
    ConnectReply {
        server_major_protocol_version: u16,
        server_minor_protocol_version: u16,
    },
    CreateIc {},
    CreateIcReply {},
    DestoryIc {},
    DestroyIcReply {},
    Disconnect {},
    DisconnectReply {},
    EncodingNegotiation {},
    EncodingNegotiationReply {},
    Error {},
    ForwardEvent {},
    Geometry {},
    GetIcValues {},
    GetIcValuesReply {},
    GetImValues {},
    GetImValuesReply {},
    Open {
        name: XimString<'b>,
    },
    OpenReply {
        input_method_id: u16,
        im_attrs: Vec<Attr<'b>>,
        ic_attrs: Vec<Attr<'b>>,
    },
    PreeditCaret {},
    PreeditCaretReply {},
    PreeditDone {},
    PreeditDraw {},
    PreeditStart {},
    PreeditStartReply {},
    PreeditState {},
    QueryExtension {
        input_method_id: u16,
        extensions: Vec<XimString<'b>>,
    },
    QueryExtensionReply {
        input_method_id: u16,
        extentions: Vec<Extension<'b>>,
    },
    RegisterTriggerKeys {},
    ResetIc {},
    ResetIcReply {},
    SetEventMask {},
    SetIcFocus {},
    SetIcValues {},
    SetIcValuesReply {},
    SetImValues {},
    SetImValuesReply {},
    StatusDone {},
    StatusDraw {},
    StatusStart {},
    StrConversion {},
    StrConversionReply {},
    Sync {},
    SyncReply {},
    TriggerNotify {},
    TriggerNotifyReply {},
    UnsetIcFocus {},
}
impl<'b> XimFormat<'b> for Request<'b> {
    fn read(reader: &mut Reader<'b>) -> Result<Self, ReadError> {
        let major_opcode = reader.u8()?;
        let minor_opcode = reader.u8()?;
        let _length = reader.u16()?;
        match (major_opcode, minor_opcode) {
            (12, _) => Ok(Request::AuthNext {}),
            (14, _) => Ok(Request::AuthNg {}),
            (11, _) => Ok(Request::AuthReply {}),
            (10, _) => Ok(Request::AuthRequired {}),
            (13, _) => Ok(Request::AuthSetup {}),
            (32, _) => Ok(Request::Close {
                input_method_id: {
                    let inner = <u16 as XimFormat<'b>>::read(reader)?;
                    u16::read(reader)?;
                    inner
                },
            }),
            (33, _) => Ok(Request::CloseReply {
                input_method_id: {
                    let inner = <u16 as XimFormat<'b>>::read(reader)?;
                    u16::read(reader)?;
                    inner
                },
            }),
            (63, _) => Ok(Request::Commit {}),
            (1, _) => Ok(Request::Connect {
                endian: {
                    let inner = <Endian as XimFormat<'b>>::read(reader)?;
                    u8::read(reader)?;
                    inner
                },
                client_major_protocol_version: <u16 as XimFormat<'b>>::read(reader)?,
                client_minor_protocol_version: <u16 as XimFormat<'b>>::read(reader)?,
                client_auth_protocol_names: {
                    let mut out = Vec::new();
                    let len = u16::read(reader)? as usize;
                    let end = reader.cursor() - len;
                    while reader.cursor() > end {
                        out.push({
                            let inner = {
                                let len = u16::read(reader)?;
                                let bytes = reader.consume(len as usize)?;
                                XimString(bytes)
                            };
                            reader.pad4()?;
                            inner
                        });
                    }
                    out
                },
            }),
            (2, _) => Ok(Request::ConnectReply {
                server_major_protocol_version: <u16 as XimFormat<'b>>::read(reader)?,
                server_minor_protocol_version: <u16 as XimFormat<'b>>::read(reader)?,
            }),
            (50, _) => Ok(Request::CreateIc {}),
            (51, _) => Ok(Request::CreateIcReply {}),
            (52, _) => Ok(Request::DestoryIc {}),
            (53, _) => Ok(Request::DestroyIcReply {}),
            (3, _) => Ok(Request::Disconnect {}),
            (4, _) => Ok(Request::DisconnectReply {}),
            (38, _) => Ok(Request::EncodingNegotiation {}),
            (39, _) => Ok(Request::EncodingNegotiationReply {}),
            (20, _) => Ok(Request::Error {}),
            (60, _) => Ok(Request::ForwardEvent {}),
            (70, _) => Ok(Request::Geometry {}),
            (56, _) => Ok(Request::GetIcValues {}),
            (57, _) => Ok(Request::GetIcValuesReply {}),
            (44, _) => Ok(Request::GetImValues {}),
            (45, _) => Ok(Request::GetImValuesReply {}),
            (30, _) => Ok(Request::Open {
                name: {
                    let inner = {
                        let len = u8::read(reader)?;
                        let bytes = reader.consume(len as usize)?;
                        XimString(bytes)
                    };
                    reader.pad4()?;
                    inner
                },
            }),
            (31, _) => Ok(Request::OpenReply {
                input_method_id: <u16 as XimFormat<'b>>::read(reader)?,
                im_attrs: {
                    let mut out = Vec::new();
                    let len = u16::read(reader)? as usize;
                    let end = reader.cursor() - len;
                    while reader.cursor() > end {
                        out.push(<Attr<'b> as XimFormat<'b>>::read(reader)?);
                    }
                    out
                },
                ic_attrs: {
                    let mut out = Vec::new();
                    let len = u16::read(reader)? as usize;
                    let end = reader.cursor() - len;
                    u16::read(reader)?;
                    while reader.cursor() > end {
                        out.push(<Attr<'b> as XimFormat<'b>>::read(reader)?);
                    }
                    out
                },
            }),
            (76, _) => Ok(Request::PreeditCaret {}),
            (77, _) => Ok(Request::PreeditCaretReply {}),
            (78, _) => Ok(Request::PreeditDone {}),
            (75, _) => Ok(Request::PreeditDraw {}),
            (73, _) => Ok(Request::PreeditStart {}),
            (74, _) => Ok(Request::PreeditStartReply {}),
            (82, _) => Ok(Request::PreeditState {}),
            (40, _) => Ok(Request::QueryExtension {
                input_method_id: <u16 as XimFormat<'b>>::read(reader)?,
                extensions: {
                    let inner = {
                        let mut out = Vec::new();
                        let len = u16::read(reader)? as usize;
                        let end = reader.cursor() - len;
                        while reader.cursor() > end {
                            out.push({
                                let len = u8::read(reader)?;
                                let bytes = reader.consume(len as usize)?;
                                XimString(bytes)
                            });
                        }
                        out
                    };
                    reader.pad4()?;
                    inner
                },
            }),
            (41, _) => Ok(Request::QueryExtensionReply {
                input_method_id: <u16 as XimFormat<'b>>::read(reader)?,
                extentions: {
                    let mut out = Vec::new();
                    let len = u16::read(reader)? as usize;
                    let end = reader.cursor() - len;
                    while reader.cursor() > end {
                        out.push(<Extension<'b> as XimFormat<'b>>::read(reader)?);
                    }
                    out
                },
            }),
            (34, _) => Ok(Request::RegisterTriggerKeys {}),
            (64, _) => Ok(Request::ResetIc {}),
            (65, _) => Ok(Request::ResetIcReply {}),
            (37, _) => Ok(Request::SetEventMask {}),
            (58, _) => Ok(Request::SetIcFocus {}),
            (54, _) => Ok(Request::SetIcValues {}),
            (55, _) => Ok(Request::SetIcValuesReply {}),
            (42, _) => Ok(Request::SetImValues {}),
            (43, _) => Ok(Request::SetImValuesReply {}),
            (81, _) => Ok(Request::StatusDone {}),
            (80, _) => Ok(Request::StatusDraw {}),
            (79, _) => Ok(Request::StatusStart {}),
            (71, _) => Ok(Request::StrConversion {}),
            (72, _) => Ok(Request::StrConversionReply {}),
            (61, _) => Ok(Request::Sync {}),
            (62, _) => Ok(Request::SyncReply {}),
            (35, _) => Ok(Request::TriggerNotify {}),
            (36, _) => Ok(Request::TriggerNotifyReply {}),
            (59, _) => Ok(Request::UnsetIcFocus {}),
            _ => {
                Err(reader.invalid_data("Opcode", format!("({}, {})", major_opcode, minor_opcode)))
            }
        }
    }
    fn write(&self, writer: &mut Writer) {
        match self {
            Request::AuthNext {} => {
                12u8.write(writer);
                0u8.write(writer);
                (((self.size() - 4) / 4) as u16).write(writer);
            }
            Request::AuthNg {} => {
                14u8.write(writer);
                0u8.write(writer);
                (((self.size() - 4) / 4) as u16).write(writer);
            }
            Request::AuthReply {} => {
                11u8.write(writer);
                0u8.write(writer);
                (((self.size() - 4) / 4) as u16).write(writer);
            }
            Request::AuthRequired {} => {
                10u8.write(writer);
                0u8.write(writer);
                (((self.size() - 4) / 4) as u16).write(writer);
            }
            Request::AuthSetup {} => {
                13u8.write(writer);
                0u8.write(writer);
                (((self.size() - 4) / 4) as u16).write(writer);
            }
            Request::Close { input_method_id } => {
                32u8.write(writer);
                0u8.write(writer);
                (((self.size() - 4) / 4) as u16).write(writer);
                input_method_id.write(writer);
                0u16.write(writer);
            }
            Request::CloseReply { input_method_id } => {
                33u8.write(writer);
                0u8.write(writer);
                (((self.size() - 4) / 4) as u16).write(writer);
                input_method_id.write(writer);
                0u16.write(writer);
            }
            Request::Commit {} => {
                63u8.write(writer);
                0u8.write(writer);
                (((self.size() - 4) / 4) as u16).write(writer);
            }
            Request::Connect {
                endian,
                client_major_protocol_version,
                client_minor_protocol_version,
                client_auth_protocol_names,
            } => {
                1u8.write(writer);
                0u8.write(writer);
                (((self.size() - 4) / 4) as u16).write(writer);
                endian.write(writer);
                0u8.write(writer);
                client_major_protocol_version.write(writer);
                client_minor_protocol_version.write(writer);
                ((client_auth_protocol_names
                    .iter()
                    .map(|e| with_pad4(e.0.len() + 2))
                    .sum::<usize>()
                    + 0
                    + 2
                    - 2) as u16)
                    .write(writer);
                for elem in client_auth_protocol_names.iter() {
                    (elem.0.len() as u16).write(writer);
                    writer.write(elem.0);
                    writer.write_pad4();
                }
            }
            Request::ConnectReply {
                server_major_protocol_version,
                server_minor_protocol_version,
            } => {
                2u8.write(writer);
                0u8.write(writer);
                (((self.size() - 4) / 4) as u16).write(writer);
                server_major_protocol_version.write(writer);
                server_minor_protocol_version.write(writer);
            }
            Request::CreateIc {} => {
                50u8.write(writer);
                0u8.write(writer);
                (((self.size() - 4) / 4) as u16).write(writer);
            }
            Request::CreateIcReply {} => {
                51u8.write(writer);
                0u8.write(writer);
                (((self.size() - 4) / 4) as u16).write(writer);
            }
            Request::DestoryIc {} => {
                52u8.write(writer);
                0u8.write(writer);
                (((self.size() - 4) / 4) as u16).write(writer);
            }
            Request::DestroyIcReply {} => {
                53u8.write(writer);
                0u8.write(writer);
                (((self.size() - 4) / 4) as u16).write(writer);
            }
            Request::Disconnect {} => {
                3u8.write(writer);
                0u8.write(writer);
                (((self.size() - 4) / 4) as u16).write(writer);
            }
            Request::DisconnectReply {} => {
                4u8.write(writer);
                0u8.write(writer);
                (((self.size() - 4) / 4) as u16).write(writer);
            }
            Request::EncodingNegotiation {} => {
                38u8.write(writer);
                0u8.write(writer);
                (((self.size() - 4) / 4) as u16).write(writer);
            }
            Request::EncodingNegotiationReply {} => {
                39u8.write(writer);
                0u8.write(writer);
                (((self.size() - 4) / 4) as u16).write(writer);
            }
            Request::Error {} => {
                20u8.write(writer);
                0u8.write(writer);
                (((self.size() - 4) / 4) as u16).write(writer);
            }
            Request::ForwardEvent {} => {
                60u8.write(writer);
                0u8.write(writer);
                (((self.size() - 4) / 4) as u16).write(writer);
            }
            Request::Geometry {} => {
                70u8.write(writer);
                0u8.write(writer);
                (((self.size() - 4) / 4) as u16).write(writer);
            }
            Request::GetIcValues {} => {
                56u8.write(writer);
                0u8.write(writer);
                (((self.size() - 4) / 4) as u16).write(writer);
            }
            Request::GetIcValuesReply {} => {
                57u8.write(writer);
                0u8.write(writer);
                (((self.size() - 4) / 4) as u16).write(writer);
            }
            Request::GetImValues {} => {
                44u8.write(writer);
                0u8.write(writer);
                (((self.size() - 4) / 4) as u16).write(writer);
            }
            Request::GetImValuesReply {} => {
                45u8.write(writer);
                0u8.write(writer);
                (((self.size() - 4) / 4) as u16).write(writer);
            }
            Request::Open { name } => {
                30u8.write(writer);
                0u8.write(writer);
                (((self.size() - 4) / 4) as u16).write(writer);
                (name.0.len() as u8).write(writer);
                writer.write(name.0);
                writer.write_pad4();
            }
            Request::OpenReply {
                input_method_id,
                im_attrs,
                ic_attrs,
            } => {
                31u8.write(writer);
                0u8.write(writer);
                (((self.size() - 4) / 4) as u16).write(writer);
                input_method_id.write(writer);
                ((im_attrs.iter().map(|e| e.size()).sum::<usize>() + 0 + 2 - 2) as u16)
                    .write(writer);
                for elem in im_attrs.iter() {
                    elem.write(writer);
                }
                ((ic_attrs.iter().map(|e| e.size()).sum::<usize>() + 2 + 2 - 2) as u16)
                    .write(writer);
                0u16.write(writer);
                for elem in ic_attrs.iter() {
                    elem.write(writer);
                }
            }
            Request::PreeditCaret {} => {
                76u8.write(writer);
                0u8.write(writer);
                (((self.size() - 4) / 4) as u16).write(writer);
            }
            Request::PreeditCaretReply {} => {
                77u8.write(writer);
                0u8.write(writer);
                (((self.size() - 4) / 4) as u16).write(writer);
            }
            Request::PreeditDone {} => {
                78u8.write(writer);
                0u8.write(writer);
                (((self.size() - 4) / 4) as u16).write(writer);
            }
            Request::PreeditDraw {} => {
                75u8.write(writer);
                0u8.write(writer);
                (((self.size() - 4) / 4) as u16).write(writer);
            }
            Request::PreeditStart {} => {
                73u8.write(writer);
                0u8.write(writer);
                (((self.size() - 4) / 4) as u16).write(writer);
            }
            Request::PreeditStartReply {} => {
                74u8.write(writer);
                0u8.write(writer);
                (((self.size() - 4) / 4) as u16).write(writer);
            }
            Request::PreeditState {} => {
                82u8.write(writer);
                0u8.write(writer);
                (((self.size() - 4) / 4) as u16).write(writer);
            }
            Request::QueryExtension {
                input_method_id,
                extensions,
            } => {
                40u8.write(writer);
                0u8.write(writer);
                (((self.size() - 4) / 4) as u16).write(writer);
                input_method_id.write(writer);
                ((extensions.iter().map(|e| e.0.len() + 1).sum::<usize>() + 0 + 2 - 2) as u16)
                    .write(writer);
                for elem in extensions.iter() {
                    (elem.0.len() as u8).write(writer);
                    writer.write(elem.0);
                }
                writer.write_pad4();
            }
            Request::QueryExtensionReply {
                input_method_id,
                extentions,
            } => {
                41u8.write(writer);
                0u8.write(writer);
                (((self.size() - 4) / 4) as u16).write(writer);
                input_method_id.write(writer);
                ((extentions.iter().map(|e| e.size()).sum::<usize>() + 0 + 2 - 2) as u16)
                    .write(writer);
                for elem in extentions.iter() {
                    elem.write(writer);
                }
            }
            Request::RegisterTriggerKeys {} => {
                34u8.write(writer);
                0u8.write(writer);
                (((self.size() - 4) / 4) as u16).write(writer);
            }
            Request::ResetIc {} => {
                64u8.write(writer);
                0u8.write(writer);
                (((self.size() - 4) / 4) as u16).write(writer);
            }
            Request::ResetIcReply {} => {
                65u8.write(writer);
                0u8.write(writer);
                (((self.size() - 4) / 4) as u16).write(writer);
            }
            Request::SetEventMask {} => {
                37u8.write(writer);
                0u8.write(writer);
                (((self.size() - 4) / 4) as u16).write(writer);
            }
            Request::SetIcFocus {} => {
                58u8.write(writer);
                0u8.write(writer);
                (((self.size() - 4) / 4) as u16).write(writer);
            }
            Request::SetIcValues {} => {
                54u8.write(writer);
                0u8.write(writer);
                (((self.size() - 4) / 4) as u16).write(writer);
            }
            Request::SetIcValuesReply {} => {
                55u8.write(writer);
                0u8.write(writer);
                (((self.size() - 4) / 4) as u16).write(writer);
            }
            Request::SetImValues {} => {
                42u8.write(writer);
                0u8.write(writer);
                (((self.size() - 4) / 4) as u16).write(writer);
            }
            Request::SetImValuesReply {} => {
                43u8.write(writer);
                0u8.write(writer);
                (((self.size() - 4) / 4) as u16).write(writer);
            }
            Request::StatusDone {} => {
                81u8.write(writer);
                0u8.write(writer);
                (((self.size() - 4) / 4) as u16).write(writer);
            }
            Request::StatusDraw {} => {
                80u8.write(writer);
                0u8.write(writer);
                (((self.size() - 4) / 4) as u16).write(writer);
            }
            Request::StatusStart {} => {
                79u8.write(writer);
                0u8.write(writer);
                (((self.size() - 4) / 4) as u16).write(writer);
            }
            Request::StrConversion {} => {
                71u8.write(writer);
                0u8.write(writer);
                (((self.size() - 4) / 4) as u16).write(writer);
            }
            Request::StrConversionReply {} => {
                72u8.write(writer);
                0u8.write(writer);
                (((self.size() - 4) / 4) as u16).write(writer);
            }
            Request::Sync {} => {
                61u8.write(writer);
                0u8.write(writer);
                (((self.size() - 4) / 4) as u16).write(writer);
            }
            Request::SyncReply {} => {
                62u8.write(writer);
                0u8.write(writer);
                (((self.size() - 4) / 4) as u16).write(writer);
            }
            Request::TriggerNotify {} => {
                35u8.write(writer);
                0u8.write(writer);
                (((self.size() - 4) / 4) as u16).write(writer);
            }
            Request::TriggerNotifyReply {} => {
                36u8.write(writer);
                0u8.write(writer);
                (((self.size() - 4) / 4) as u16).write(writer);
            }
            Request::UnsetIcFocus {} => {
                59u8.write(writer);
                0u8.write(writer);
                (((self.size() - 4) / 4) as u16).write(writer);
            }
        }
    }
    fn size(&self) -> usize {
        let mut content_size = 0;
        match self {
            Request::AuthNext {} => {}
            Request::AuthNg {} => {}
            Request::AuthReply {} => {}
            Request::AuthRequired {} => {}
            Request::AuthSetup {} => {}
            Request::Close { input_method_id } => {
                content_size += input_method_id.size() + 2;
            }
            Request::CloseReply { input_method_id } => {
                content_size += input_method_id.size() + 2;
            }
            Request::Commit {} => {}
            Request::Connect {
                endian,
                client_major_protocol_version,
                client_minor_protocol_version,
                client_auth_protocol_names,
            } => {
                content_size += endian.size() + 1;
                content_size += client_major_protocol_version.size();
                content_size += client_minor_protocol_version.size();
                content_size += client_auth_protocol_names
                    .iter()
                    .map(|e| with_pad4(e.0.len() + 2))
                    .sum::<usize>()
                    + 0
                    + 2;
            }
            Request::ConnectReply {
                server_major_protocol_version,
                server_minor_protocol_version,
            } => {
                content_size += server_major_protocol_version.size();
                content_size += server_minor_protocol_version.size();
            }
            Request::CreateIc {} => {}
            Request::CreateIcReply {} => {}
            Request::DestoryIc {} => {}
            Request::DestroyIcReply {} => {}
            Request::Disconnect {} => {}
            Request::DisconnectReply {} => {}
            Request::EncodingNegotiation {} => {}
            Request::EncodingNegotiationReply {} => {}
            Request::Error {} => {}
            Request::ForwardEvent {} => {}
            Request::Geometry {} => {}
            Request::GetIcValues {} => {}
            Request::GetIcValuesReply {} => {}
            Request::GetImValues {} => {}
            Request::GetImValuesReply {} => {}
            Request::Open { name } => {
                content_size += with_pad4(name.0.len() + 1);
            }
            Request::OpenReply {
                input_method_id,
                im_attrs,
                ic_attrs,
            } => {
                content_size += input_method_id.size();
                content_size += im_attrs.iter().map(|e| e.size()).sum::<usize>() + 0 + 2;
                content_size += ic_attrs.iter().map(|e| e.size()).sum::<usize>() + 2 + 2;
            }
            Request::PreeditCaret {} => {}
            Request::PreeditCaretReply {} => {}
            Request::PreeditDone {} => {}
            Request::PreeditDraw {} => {}
            Request::PreeditStart {} => {}
            Request::PreeditStartReply {} => {}
            Request::PreeditState {} => {}
            Request::QueryExtension {
                input_method_id,
                extensions,
            } => {
                content_size += input_method_id.size();
                content_size +=
                    with_pad4(extensions.iter().map(|e| e.0.len() + 1).sum::<usize>() + 0 + 2);
            }
            Request::QueryExtensionReply {
                input_method_id,
                extentions,
            } => {
                content_size += input_method_id.size();
                content_size += extentions.iter().map(|e| e.size()).sum::<usize>() + 0 + 2;
            }
            Request::RegisterTriggerKeys {} => {}
            Request::ResetIc {} => {}
            Request::ResetIcReply {} => {}
            Request::SetEventMask {} => {}
            Request::SetIcFocus {} => {}
            Request::SetIcValues {} => {}
            Request::SetIcValuesReply {} => {}
            Request::SetImValues {} => {}
            Request::SetImValuesReply {} => {}
            Request::StatusDone {} => {}
            Request::StatusDraw {} => {}
            Request::StatusStart {} => {}
            Request::StrConversion {} => {}
            Request::StrConversionReply {} => {}
            Request::Sync {} => {}
            Request::SyncReply {} => {}
            Request::TriggerNotify {} => {}
            Request::TriggerNotifyReply {} => {}
            Request::UnsetIcFocus {} => {}
        }
        content_size + 4
    }
}
